Employer.create(name: 'Urtu', username: 'urtu', password: 'phoenix', company_name: 'Urtu Inc.')
Employee.create(name: 'Ryan Kwon', username: 'rhk1', password: 'phoenix', employer_id: 1)
QrCode.create(location: "Stuff1", content: "Hey", company_id: "1")
QrCode.create(location: "Stuff2", content: "Hey", company_id: "1")
QrCode.create(location: "Stuff3", content: "Hey", company_id: "1")
QrCode.create(location: "Stuff4", content: "Hey", company_id: "1")
QrCode.create(location: "Stuff5", content: "Hey", company_id: "1")
QrCode.create(location: "Stuff6", content: "Hey", company_id: "1")